### ISSUE TITLE
Feature Requst: Mob drop search

### ISSUE THREAD

**Issue by WolfGaming** [shagu/ShaguQuest#1]
I like this addon a lot, but would it be possible to search for a mob and display all the items he drops with the percantages?

**Comment by shagu** [comment]
Sounds good! I'll have a look.
Thanks

**Comment by WolfGaming** [comment]
Nice, Ill wait for the feature with eagerness :+1:

**Comment by Muehe** [comment]
This will be hard due to the way mangos-style servers organise loot. Items are put in groups which can have sub-groups. This data is more than 10 MB in the current cmangos classicdb, if you sort it by item it grows to 22 MB, due to some mobs/objects/items sharing the same loot groups ([see here](https://github.com/cmangos/issues/wiki/Loot_Template) for more info). I was thinking of using groups instead of by-item data and adding a lookup table, but so far thats just an idea and I am not sure how performant this would be.

**Comment by shagu** [comment]
This won't happen here, but you might want to have a look at the fork:
https://github.com/Muehe/classicdb
