### ISSUE TITLE
Icons on map for availible quests

### ISSUE THREAD

**Issue by byaka** [shagu/ShaguQuest#15]
This addon is perfect alternative for questie addon, but it missing ability to show icons for availible quests. So for now i need to enable both addons.
Can u pls add this fucntion if it not hard?

**Comment by byaka** [comment]
ok, its duplicate for #5

**Comment by Muehe** [comment]
Hey there, just wanted to let you know the addon I was developing as ShaguQuest 8 has been moved [here](https://github.com/Muehe/classicdb), because shagu is preoccupied with pfUI and other things. The quest start feature in the currently available beta is a little rough, because tracking accepted and finished quests is bugged and therefore display of quest chains might be off. Working on a solution to that though.

**Comment by byaka** [comment]
Oh, thx u! Im finded your addon 3 days ago but read description and thinking it's only db and  view-ui for search.
