### ISSUE TITLE
Small lag after partial Quest completion

### ISSUE THREAD

**Issue by Suzaru** [shagu/ShaguQuest#20]
Hey,

if I let's say kill 1 of 10 Syndicate Rogues, my screen lags for a short amount of time.
This doesnt happen, when ShaguQuest is deactivated.

Any idea?

Thanks

**Comment by Muehe** [comment]
This usually only happens when you have auto-tracking enabled and some quest in your quest log requires a very common item. Good examples would be the pages quests in Stranglethorn or quests requiring silk cloth. There are a few possible solutions:

1. Abandon the quest(-s) causing the problem. Cloth items and Stranglethorn pages can be looted while you are not on the quest
2. Disable auto-track and manually track quests instead, as long as you are on the quest(-s) causing the problem.
3. Shagu is not actively developing this addon anymore, but I made a fork, [ClassicDB](https://github.com/Muehe/classicdb/releases). It has this issue as well, but due to the way notes are handled before sending them to Cartographer (which is the real bottleneck), the issue is less bad. I have a test char for this, which has all the Stranglethorn Chapter quests and two quests requiring Silk Cloth, and the lag is barely noticeable. You can find a list of changes since ShaguQuest 7.2 [here](https://github.com/Muehe/classicdb/blob/master/CHANGELOG.md).

**Comment by shagu** [comment]
This project is abandoned and has been superseeded by pfQuest (https://github.com/shagu/pfQuest).

This issue is no longer valid for the new pfQuest addon.
