### ISSUE TITLE
Avalible quests

### ISSUE THREAD

**Issue by chazragg** [shagu/shaguquest#5]
the command /shagu quests is great but kind of useless at the same time you should make it so it only show available quests so as you level you can see what quests you can pick up instead of seeing ever quest giver

**Comment by Schaka** [comment]
There's no way of knowing in vanilla if a quest has already been completed.

**Comment by chazragg** [comment]
Questie does it. granted it does mess up sometime but then it has a command /questie complete "queste name"

**Comment by Schaka** [comment]
Look, I'm one of the Questie developers and I am telling you tehre is no way.
Questie hooks several game element functions WHILE YOU PLAY to GUESS whether you already picked up and/or finished a quest.

It is not possible. Unless ShaguQuest does the same thing and then double checks against quests you've already done. It won't work afterwards though, so it's already too late.

**Comment by chazragg** [comment]
so you can still implement some sort of feature weather it is guessing or not to track quests ? you just said it your self "It is not possible. Unless ShaguQuest does the same thing and then double checks against quests you've already done." so why you it be done in questeis and not shagu ?"

**Comment by Schaka** [comment]
Because it's already too late. You need to have the addon enabled while you finish quests. You cannot check in hindsight whether a quest was completed or not. Maybe I'm not expressing myself right. I don't mean to come off as aggressive.

But you need to run the addon the entire time and it will keep track of your completed quests. So the functionality you asked for would only be possible in that specific scenario.

**Comment by chazragg** [comment]
i under stand that and i understood it from the start but my point still stand you can still implement the feature so when people create a new character it will start tracking. i understand the my lvl 14 warlock wont have all the previous quests i have done ticked off but that is not my point my point is the feature exists in some form and still can be implemented even with the limitation of using it on an already level character

**Comment by Muehe** [comment]
This is somewhere on the bottom of my TODO before merging my addon into ShaguQuest. Should be fairly easy to add a quest finishing/hiding button in the search UI.

**Comment by Muehe** [comment]
@chazragg I just created a [pre-release](https://github.com/shagu/shaguquest/releases/tag/8.0-alpha.1). It shows more info in the tooltip (e.g. multiple quests) and there are chat commands to hide quests forever by ID or based on required level. Feedback would be very welcome (a button to hide quests is going to be added once the search GUI has been fixed).

**Comment by baaja** [comment]
Is there a way to toggle the notes that come from ShaguQuest, since I am using Questie I want to have them and thus not have double markers/notes on my map. Thanks!

**Comment by Muehe** [comment]
@baaja I think there is an option in Cartographer to hide all notes, which should hide all notes from ShaguQuest, but not those from Questie, since they are using a different system for displaying notes. If that is not the case there is an option for this in the current version of the 8.0 branch, but if you don't know how to use shell scripts I'd have to make a new alpha release (current one is buggy).

**Comment by Muehe** [comment]
@baaja The new UI in the 8.0 beta has buttons for hiding ShaguQuest notes and another one for hiding Questie Notes.

@chazragg With the new beta release I consider this feature implemented. If you find bugs please create a new issue. Thank you.
